### ISSUE TITLE
Server Config File

### ISSUE THREAD

**Issue by ThesiiNCey** [girlbossceo/conduwuit#214]
i want to create a server inside docker but the server is not loading the toml config

Here my Compose File
```
version: '2.4' # uses '2.4' for cpuset

services:
    homeserver:
        image: ghcr.io/girlbossceo/conduwuit:latest
        restart: unless-stopped
        ports:
            - 6167:6167
        volumes:
            - ./db:/var/lib/matrix-conduit
            - ./config:/etc/conduwuit/
        environment:
            CONDUIT_CONFIG: ./conduwuit.toml
        cpuset: "0-2"


    cinny:
        image: ghcr.io/cinnyapp/cinny:latest
        container_name: cinny
        restart: unless-stopped
        ports:
          - 8182:80

volumes:
    db:
```

Actually, that's how it's supposed to work, isn't it? I don't have to enter all the environment things when I load a config, right?
