### ISSUE TITLE
Confuse what is the right setup via docker image

### ISSUE THREAD

**Issue by killua99** [girlbossceo/conduwuit#465]
Currently, I'm trying to figure out which docker-compose.* is the latest and the most updated to the current image hosted at https://github.com/girlbossceo/conduwuit/pkgs/container/conduwuit

We have several files at https://github.com/girlbossceo/conduwuit/tree/main/docs/deploying, which every single of them has the environment definition with differences and the docker run time also bring different environment variables.

Which one would be the latest, most updated? Also, where could I find the Dockerfile file? I don't see it, or this build time is so new to me that I will be so happy to know where could I read that file.

**Comment by girlbossceo** [comment]
> the most updated to the current image hosted at 

See the Docker page on our website/documentation: https://conduwuit.puppyirl.gay/deploying/docker.html

> Currently, I'm trying to figure out which docker-compose.* is the latest

> which every single of them has the environment definition with differences and the docker run time also bring different environment variables.

> Which one would be the latest, most updated?

These are community maintained and I cannot make any guarantees about them. I do not use anything container related, including Docker, so even most of the Docker stuff here is community maintained. We do have some Docker users, and some who use Docker Compose, but I myself do not and I don't know anything about it. Feel free to join the Matrix room and ask about that for those users.

I have a slight interest in deleting these Compose files except for one due to the confusion this has seemed to cause, and if someone wants to use Traefik or whatever, they can look at the tons of documentation online at figuring that out. But since these are community maintained, I'll probably leave them.

>  Also, where could I find the Dockerfile file? 

We do not have a Dockerfile as it quickly fell behind on staying up to date, lack of testing or usage and contributions by anyone, and is another complex piece that would need to be maintained especially for something I don't use myself.

We only have prebuilt OCI images that are published at the registries listed on the conduwuit documentation/website. In theory a Dockerfile could be generated through our CI via Nix but this isn't something I'm interested in as I've already gone to great lengths more than I should have to get even reproducible and consistent OCI images updated and working.

**Comment by killua99** [comment]
Thanks for the quick response. I understand the burden that mean maintaining such a project like this one.

The documentation docker shows different setup that is why I'm asking, I was trying to build my matrix to connect to others rooms if I understood correctly, I understand if I create a user I could migrate it to my instance. Just wanted to try to install my server to avoid the migration process.

Dockerfile could have tests on CI/pipelines, but once I understand what is missing from the current docs and build, I might be able to write a PR.

Thanks for the info

**Comment by girlbossceo** [comment]
> Dockerfile could have tests on CI/pipelines, but once I understand what is missing from the current docs and build, I might be able to write a PR.

We already have multiple forms of testing or inherent testing:
- Integration testing via engage which tests feature matrixes, dependencies, linting, formatting, documentation, etc
- Fully static x86_64 and arm64 builds (does the codebase even build)
- Complement for part Matrix spec compliance and an inherent conduwuit smoke / basic load test
- and all of this is done under the Nix infrastructure which inherently tests basic Nix functionality and our entire CI setup

I don't see how throwing Docker into this would be of any value and I don't think I would accept a PR for this. It would be another build system to maintain. Everything here is done through Nix and I would only accept a PR for Dockerfile generation if it was fully done through Nix.

Our OCI images have been working very fine for all the Docker users, even the Compose users, and is aligned with our static builds as it uses the same binaries there and is distroless / minimal.

**Comment by killua99** [comment]
Understood

In that case, a PR that clear the doubt how to start a server via docker

**Comment by Crementif** [comment]
Just thought I'd chime in considering I did put some time into setting it up just today (did end up using Caddy instead of Traefik, since I couldn't get it to work, although that might just be me) using the provided documentation, so I thought it'd be helpful! Also, thanks for the work on this server! I hope that the following will help in any way.

Here's most of my setup, although note that while its working, it is still work-in-progress.
https://gist.github.com/Crementif/afb2e66c77106a4dbb0c5bb6fd89fb38#file-docker-compose-yml.

--- 

Now, here's some things I noticed while reading the documentation. Not entirely sure if all of them are correct:

 * I had to set the environment variable CONDUWUIT_CONFIG to `/etc/conduwuit.toml` instead of `./conduwuit.toml`.
```yml
        volumes:
[...]
            #- ./conduwuit.toml:/etc/conduwuit.toml
[...]
            #CONDUWUIT_CONFIG: './conduwuit.toml' # Uncomment if you mapped config toml above
```
* The db volume path in the `docker-compose.with-traefik.yml` is not like the other docker-compose examples. Should be fine however, just be careful not to mix the two up.
* I'm not that experienced with Traefik, but I also noticed that the well-known service lacks the networks: proxy label. Not sure if that is required for Traefik, but I thought I'd mention it.

Something to keep in mind is that you need the docker-compose.override.yml file when using the Traefik docker-compose files.

**Comment by girlbossceo** [comment]
> I think a lot of these options are overwritten by the config file

More than half of these are, yes, though I believe upstream kept them in just because it made it "more obvious" how to edit some things of your config. I should probably clean that up and just leave a link to our example config.

If you'd like to, I'll accept a PR that fixes, cleans up, and simplifies the Compose files. If not I'll take a look at your yaml file there and see what I can change/replace.

**Comment by Crementif** [comment]
Thanks for the quick reply. I'm fairly busy at the moment, but I could contribute some of it on a later date, if using Caddy instead of Traefik is acceptable. Or maybe @killua99 could maybe try if they were planning on using Traefik. I've still got some issues left, but I'll make a new issue for that.

**Comment by killua99** [comment]
I can take a look later ofc, I use traefik for all my containers, so I'll attempt one more time looking your config files and adapt them to traefik.

I guess we can clear out few unnecessary files like the override yaml file

**Comment by rattencreep** [comment]
Maybe this is useful getting things to work with traefik. I am new to conduwuit and matrix in general, so I just tried to get a basic server running yesterday. This is my docker compose file that works.

```
---
networks:
  proxy:
    external: true
    
volumes:
  database:

services:
  conduwuit:
    image: girlbossceo/conduwuit:latest
    restart: always
    volumes:
      - database:/var/lib/conduwuit
    container_name: conduwuit
    environment:
      CONDUWUIT_SERVER_NAME: sub.domain.tld
      CONDUWUIT_DATABASE_PATH: /var/lib/conduwuit
      CONDUWUIT_DATABASE_BACKEND: rocksdb
      CONDUWUIT_PORT: 6167
      CONDUWUIT_MAX_REQUEST_SIZE: 20_000_000
      CONDUWUIT_ALLOW_REGISTRATION: 'true'
      CONDUWUIT_REGISTRATION_TOKEN: redacted
      CONDUWUIT_ALLOW_FEDERATION: 'false'
      CONDUWUIT_ALLOW_CHECK_FOR_UPDATES: 'false'
      CONDUWUIT_TRUSTED_SERVERS: '["matrix.org"]'
      CONDUWUIT_ADDRESS: 0.0.0.0
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.conduwuit.rule=Host(`sub.domain.tld`)"
      - "traefik.http.services.conduwuit.loadbalancer.server.port=6167"
      - "traefik.http.routers.conduwuit.tls=true"
      - "traefik.http.routers.conduwuit.tls.certresolver=production"
      - "traefik.http.routers.conduwuit.middlewares=cors-headers@docker"
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=Origin, X-Requested-With, Content-Type, Accept, Authorization"
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=GET, POST, PUT, DELETE, OPTIONS"
```
