### ISSUE TITLE
Add [global.config] in conduwuit-example.toml

### ISSUE THREAD

**Issue by wenxuanjun** [girlbossceo/conduwuit#591]
Conduwuit supports setting proxy and its code is located in `src/core/config/proxy.rs`.

Example config in code (need to add details of configuration items):

```toml
[global.proxy]
global = { url = "socks5h://localhost:9050" }

[[global.proxy.by_domain]]
url = "socks5h://localhost:9050"
include = ["*.onion", "matrix.myspecial.onion"]
exclude = ["*.myspecial.onion"]
```

**Comment by girlbossceo** [comment]
Has anyone validated if this proxy code still works in conduwuit? It's been pretty much untouched since we forked.

**Comment by wenxuanjun** [comment]
I have tried these two config and  they seem to work fine (my server can't connect directly to matrix.org due to special network environment).

```toml
# [global.proxy]
# global = { url = "http://127.0.0.1:8080" }
```

```toml
[[global.proxy.by_domain]]
url = "http://127.0.0.1:8080"
include = ["*.onion", "matrix.org", "*.matrix.org"]
```

But I didn't test `exclude`, and do not have a good way to get detailed logs to prove the proxy usage of conduwuit.
