### ISSUE TITLE
Mautrix-WhatsApp Appservice not responding (Conduwuit, No Docker) – API returns 404

### ISSUE THREAD

**Issue by jolichter** [girlbossceo/conduwuit#700]
## Hello, could someone perhaps help or share some tips? Or is anyone running Conduwuit with Mautrix-WhatsApp natively (without Docker)?

# Current setup:
I have Conduwuit and Mautrix-WhatsApp installed natively (without Docker).

## Issue:
The bridge is not working properly:

- Conduwuit and Element (Web) are working fine.
- Mautrix-WhatsApp is set up but not responding.
- No response to `!wa help` in the admin room.
- Port **29318** is open, and Mautrix-WhatsApp is listening on it.
- Conduwuit shows the appservice as registered (`!admin appservices list`).
- The appservice configuration (`show-appservice-config`) looks correct.
- The bridge is making sync requests to Conduwuit (confirmed in `bridge.log`).
- However, API calls return **404 (not found).**

---

### Check if the appservice API is responding:
```
curl -X GET http://127.0.0.1:29318/_matrix/app/v1/users
```
**Response:**
`404 page not found` (Appservice is not active or not responding)

### Test with `as_token`:
```
curl -X GET -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" http://127.0.0.1:29318/_matrix/app/v1/users
```
**Response:**
`404 page not found`

### Check if the bridge API is enabled:
```
curl -X GET http://127.0.0.1:29318
```
**Response:**
`404 page not found`

### Test if transactions API is available:
```
curl -X GET "http://127.0.0.1:29318/_matrix/app/v1/transactions/1"
```
**Response:**
**Empty response** → Mautrix-WhatsApp is not responding.

---

### Test forwarding requests to Conduwuit:
```
curl -X GET -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \
http://127.0.0.1:6167/_matrix/client/v3/sync?user_id=@whatsappbot:lmatrix.de
```
**Response:**
```json
{
  "details": "user must be authenticated and device identified",
  "errcode": "M_UNKNOWN",
  "error": "M_UNKNOWN: Internal server error occurred"
}
```
Error message: **"M_UNKNOWN: Internal server error occurred"**

---

## Checking Appservice Registration

```
!admin appservices list
```
**Output:**
```
Appservices (1): whatsapp
```
Appservice is registered correctly in Conduwuit.

### Verify if the appservice port is open:
```
sudo netstat -tulpen | grep 29318
```
**Output:**
```
tcp        0      0 127.0.0.1:29318         0.0.0.0:*               LISTEN      103        34069      1673/mautrix-whatsa
```
📝 (Note: The truncated output `mautrix-whatsa` instead of `mautrix-whatsapp` is due to column width limitations in `netstat`.)

### Check appservice config in Element:
The tokens match `/opt/mautrix-whatsapp/registration.yaml`
```
!admin appservices show-appservice-config whatsapp
```
**Output:**
```yaml
id: whatsapp
url: http://localhost:29318
as_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
hs_token: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
sender_localpart: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
namespaces:
  users:
  - exclusive: true
    regex: ^@whatsappbot:lmatrix\.de$
  - exclusive: true
    regex: ^@whatsapp_.*:lmatrix\.de$
rate_limited: false
receive_ephemeral: true
```

---

## System Information

- **OS:** Debian GNU/Linux 12 (bookworm) x86_64
- **Kernel:** 6.1.0-31-amd64
- **Conduwuit:** 0.5.0
- **rust:** 1.85.0
- **cargo:** 1.85.0
- **node:** v20.18.3
- **npm:** 10.8.2
- **Element (Web):** 1.11.94
- **go:** 1.24.1
- **Mautrix-WhatsApp:** v0.11.3

---

## Question:
Why does the appservice API return **404**?
It appears that:
1. The bridge is running and listening on port **29318**.
2. The appservice is registered in Conduwuit.
3. The bridge is making sync requests to Conduwuit.
4. However, API calls to the bridge return **404**, meaning the appservice does not respond.

What could be missing or misconfigured? Any advice is greatly appreciated! 🚀
