### ISSUE TITLE
bridge (mautrix-whatsapp) is running, but returns 404

### ISSUE THREAD

**Issue by jolichter** [girlbossceo/conduwuit#703]
Hallo, I have a trouble with the Mautrix-WhatsApp, which is supposed to run under Conduwuit.

I realize that it is a third party program, but maybe someone has an idea or tips? Or are they incompatible?

I have inserted the content of the created registration.yaml like this (token masked):

```
!admin appservices register
id: whatsapp
url: http://127.0.0.1:29318
as_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
hs_token: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
sender_localpart: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
rate_limited: false
namespaces:
    users:
        - regex: ^@whatsappbot:lmatrix\.de$
          exclusive: true
        - regex: ^@whatsapp_.*:lmatrix\.de$
          exclusive: true
de.sorunome.msc2409.push_ephemeral: true
receive_ephemeral: true
```

Then checked:
```
!admin appservices list
Appservices (1): whatsapp
```

Unfortunately, the bridge does not respond to requests. e.g.: `!WA help` gives no response.

```
netstat -tulpen | grep 29318
tcp        0      0 127.0.0.1:29318         0.0.0.0:*               LISTEN      103        25403      1353/mautrix-whatsa 
curl -X GET http://127.0.0.1:29318/_matrix/app/v1/users
404 page not found
curl -X GET http://127.0.0.1:29318
404 page not found
```

The bridge seems to be running, but returns 404?
